// Package workspace resolves and validates per-job workspace paths.
//
// docs/sandbox-executor.md §9.3 specifies the rules: the controller composes
// the host path from the configured workdir root + traceId + repoSlug, then
// canonicalises via filepath.EvalSymlinks and asserts the result stays under
// the root. Non-existent paths, .. traversal attempts, and symlinks pointing
// out of the root are all rejected with workspace_invalid.
package workspace

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ErrWorkspaceInvalid is returned for any path-validation failure. Callers
// surface it as the wire-format error code workspace_invalid.
var ErrWorkspaceInvalid = errors.New("workspace_invalid")

// Validator resolves and validates per-trace workspace paths against a
// configured root. The root is canonicalised once at construction so each
// Resolve call only has to canonicalise the candidate.
type Validator struct {
	root        string
	resultsDir  string
}

// New returns a Validator. workdirRoot must be absolute and existing;
// resultsDir is the per-trace results subdirectory name (default ".results").
func New(workdirRoot, resultsDir string) (*Validator, error) {
	if workdirRoot == "" {
		return nil, fmt.Errorf("workspace: workdir root is empty")
	}
	if !filepath.IsAbs(workdirRoot) {
		return nil, fmt.Errorf("workspace: workdir root %q must be absolute", workdirRoot)
	}
	resolved, err := filepath.EvalSymlinks(workdirRoot)
	if err != nil {
		return nil, fmt.Errorf("workspace: cannot resolve workdir root %q: %w", workdirRoot, err)
	}
	info, err := os.Stat(resolved)
	if err != nil || !info.IsDir() {
		return nil, fmt.Errorf("workspace: workdir root %q is not a directory", resolved)
	}
	if resultsDir == "" {
		resultsDir = ".results"
	}
	if strings.ContainsAny(resultsDir, `/\`) {
		return nil, fmt.Errorf("workspace: results dir name %q must be a single segment", resultsDir)
	}
	return &Validator{root: resolved, resultsDir: resultsDir}, nil
}

// Root returns the canonical workdir root the validator is anchored at.
func (v *Validator) Root() string { return v.root }

// ResultsDirName returns the configured per-trace results subdirectory name.
func (v *Validator) ResultsDirName() string { return v.resultsDir }

// Resolved is the output of Resolve: canonical host paths the runner will
// hand to dockerd as bind-mount sources.
type Resolved struct {
	// Workspace is the canonical host path mounted into the sandbox at
	// /workspace (read-only).
	Workspace string

	// Results is the canonical host path mounted into the sandbox at
	// /artifacts (read-write). Lives under
	// {root}/{traceId}/{resultsDir}/{jobId}/. Created if absent.
	Results string
}

// Resolve composes and validates the workspace + results paths for one job.
// traceId and (optional) repoSlug are caller-supplied (already strict-decoded
// by the handler). jobId is generated by the api/worker per-job.
//
// repoSlug is a vestigial knob retained for the wire-format migration: when
// empty, the workspace is the trace dir itself (`{root}/{traceId}/`), which
// matches the unified `/workspace/{traceId}` layout introduced when the
// per-trace workdir was made writable. When non-empty, the legacy
// `{root}/{traceId}/{repoSlug}/` layout is used so callers that haven't
// migrated yet still resolve.
//
// Validation rules (§9.3):
//   - traceId / repoSlug / jobId must not contain path separators or ".."
//   - workspace path must canonicalise to a path under the configured root
//   - workspace path must be an existing directory
//   - the results dir is created on demand under the validated trace dir
func (v *Validator) Resolve(traceId, repoSlug, jobId string) (*Resolved, error) {
	if err := safeSegment("traceId", traceId); err != nil {
		return nil, err
	}
	if err := safeSegment("jobId", jobId); err != nil {
		return nil, err
	}
	// repoSlug is optional. When provided, validate as a single segment.
	if repoSlug != "" {
		if err := safeSegment("repoSlug", repoSlug); err != nil {
			return nil, err
		}
	}

	traceDir := filepath.Join(v.root, traceId)
	traceCanon, err := filepath.EvalSymlinks(traceDir)
	if err != nil {
		return nil, fmt.Errorf("%w: trace dir %q does not exist", ErrWorkspaceInvalid, traceId)
	}
	if !underRoot(v.root, traceCanon) {
		return nil, fmt.Errorf("%w: trace dir %q escapes configured root", ErrWorkspaceInvalid, traceId)
	}

	workspaceCanon := traceCanon
	if repoSlug != "" {
		repoDir := filepath.Join(traceCanon, repoSlug)
		repoCanon, err := filepath.EvalSymlinks(repoDir)
		if err != nil {
			return nil, fmt.Errorf("%w: repo dir %q does not exist", ErrWorkspaceInvalid, repoSlug)
		}
		if !underRoot(v.root, repoCanon) {
			return nil, fmt.Errorf("%w: repo dir %q escapes configured root", ErrWorkspaceInvalid, repoSlug)
		}
		info, err := os.Stat(repoCanon)
		if err != nil || !info.IsDir() {
			return nil, fmt.Errorf("%w: repo dir %q is not a directory", ErrWorkspaceInvalid, repoSlug)
		}
		workspaceCanon = repoCanon
	} else {
		// Trace dir is the workspace; confirm it's a directory (EvalSymlinks above
		// would have failed if it didn't exist, but we still want to reject a file
		// or device entry — defence in depth).
		info, err := os.Stat(workspaceCanon)
		if err != nil || !info.IsDir() {
			return nil, fmt.Errorf("%w: trace dir %q is not a directory", ErrWorkspaceInvalid, traceId)
		}
	}

	resultsDir := filepath.Join(traceCanon, v.resultsDir, jobId)
	if err := os.MkdirAll(resultsDir, 0o770); err != nil {
		return nil, fmt.Errorf("%w: cannot create results dir: %v", ErrWorkspaceInvalid, err)
	}
	// Re-canonicalise so a symlinked .results doesn't escape (defence in depth;
	// MkdirAll above wouldn't have followed an out-of-tree symlink anyway).
	resultsCanon, err := filepath.EvalSymlinks(resultsDir)
	if err != nil {
		return nil, fmt.Errorf("%w: results dir resolution failed: %v", ErrWorkspaceInvalid, err)
	}
	if !underRoot(v.root, resultsCanon) {
		return nil, fmt.Errorf("%w: results dir escapes configured root", ErrWorkspaceInvalid)
	}

	return &Resolved{Workspace: workspaceCanon, Results: resultsCanon}, nil
}

// underRoot reports whether `path` is `root` itself or a descendant. Both
// sides should already be EvalSymlinks-canonical.
func underRoot(root, path string) bool {
	rootSep := strings.TrimRight(root, string(filepath.Separator)) + string(filepath.Separator)
	if path == root {
		return true
	}
	return strings.HasPrefix(path, rootSep)
}

// safeSegment rejects path-traversal attempts in a single ID. Allowed: any
// non-empty string that does not contain a path separator and is not "."
// or "..". This is intentionally narrow — traceId / repoSlug / jobId are
// CodeFlow-side opaque tokens, not user-typed paths.
func safeSegment(name, s string) error {
	s = strings.TrimSpace(s)
	if s == "" {
		return fmt.Errorf("%w: %s is empty", ErrWorkspaceInvalid, name)
	}
	if s == "." || s == ".." {
		return fmt.Errorf("%w: %s cannot be %q", ErrWorkspaceInvalid, name, s)
	}
	if strings.ContainsAny(s, `/\`) || strings.Contains(s, "..") {
		return fmt.Errorf("%w: %s %q contains a path separator or ..", ErrWorkspaceInvalid, name, s)
	}
	return nil
}
