// <auto-generated />
using System;
using CodeFlow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFlow.Persistence.Migrations
{
    [DbContext(typeof(CodeFlowDbContext))]
    [Migration("20260423111627_AddSubflowSupport")]
    partial class AddSubflowSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CodeFlow.Persistence.AgentConfigEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRetired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_retired");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key", "IsActive");

                    b.HasIndex("Key", "IsRetired");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleAssignmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("agent_key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("AgentKey");

                    b.HasIndex("RoleId");

                    b.HasIndex("AgentKey", "RoleId")
                        .IsUnique();

                    b.ToTable("agent_role_assignments", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("agent_roles", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleSkillGrantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("RoleId", "SkillId")
                        .IsUnique();

                    b.ToTable("agent_role_skill_grants", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleToolGrantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("category");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<string>("ToolIdentifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("tool_identifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "Category", "ToolIdentifier")
                        .IsUnique();

                    b.ToTable("agent_role_tool_grants", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.GitHostSettingsEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("key");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("base_url");

                    b.Property<byte[]>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("varbinary(1024)")
                        .HasColumnName("encrypted_token");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("mode");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Key");

                    b.ToTable("git_host_settings", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.HitlTaskEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("agent_key");

                    b.Property<int>("AgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("agent_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("decided_at");

                    b.Property<string>("DeciderId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("decider_id");

                    b.Property<int?>("Decision")
                        .HasColumnType("int")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionPayloadJson")
                        .HasColumnType("longtext")
                        .HasColumnName("decision_payload_json");

                    b.Property<string>("InputPreview")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("input_preview");

                    b.Property<string>("InputRef")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("input_ref");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("node_id");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("round_id");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("workflow_key");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("int")
                        .HasColumnName("workflow_version");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("TraceId", "RoundId", "AgentKey");

                    b.ToTable("hitl_tasks", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.McpServerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("BearerTokenCipher")
                        .HasColumnType("varbinary(1024)")
                        .HasColumnName("bearer_token_cipher");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("endpoint_url");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Unverified")
                        .HasColumnName("health_status");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<string>("LastVerificationError")
                        .HasColumnType("text")
                        .HasColumnName("last_verification_error");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("transport");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("mcp_servers", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.McpServerToolEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsMutating")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_mutating");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("longtext")
                        .HasColumnName("parameters_json");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("synced_at");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "ToolName")
                        .IsUnique();

                    b.ToTable("mcp_server_tools", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.SkillEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowEdgeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("from_node_id");

                    b.Property<string>("FromPort")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("from_port");

                    b.Property<bool>("RotatesRound")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("rotates_round");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("to_node_id");

                    b.Property<string>("ToPort")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("to_port");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "FromNodeId", "FromPort", "SortOrder");

                    b.ToTable("workflow_edges", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<int>("MaxRoundsPerRound")
                        .HasColumnType("int")
                        .HasColumnName("max_rounds_per_round");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowInputEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DefaultValueJson")
                        .HasColumnType("longtext")
                        .HasColumnName("default_value_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("kind");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("required");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Key")
                        .IsUnique();

                    b.ToTable("workflow_inputs", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowNodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("agent_key");

                    b.Property<int?>("AgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("agent_version");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<double>("LayoutX")
                        .HasColumnType("double")
                        .HasColumnName("layout_x");

                    b.Property<double>("LayoutY")
                        .HasColumnType("double")
                        .HasColumnName("layout_y");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("node_id");

                    b.Property<string>("OutputPortsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("output_ports_json");

                    b.Property<string>("Script")
                        .HasColumnType("longtext")
                        .HasColumnName("script");

                    b.Property<string>("SubflowKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("subflow_key");

                    b.Property<int?>("SubflowVersion")
                        .HasColumnType("int")
                        .HasColumnName("subflow_version");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "NodeId")
                        .IsUnique();

                    b.ToTable("workflow_nodes", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaDecisionEntity", b =>
                {
                    b.Property<Guid>("SagaCorrelationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("saga_correlation_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("agent_key");

                    b.Property<int>("AgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("agent_version");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionPayloadJson")
                        .HasColumnType("longtext")
                        .HasColumnName("decision_payload_json");

                    b.Property<string>("InputRef")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("input_ref");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("node_id");

                    b.Property<string>("OutputPortName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("output_port_name");

                    b.Property<string>("OutputRef")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("output_ref");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("round_id");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.HasKey("SagaCorrelationId", "Ordinal");

                    b.HasIndex("TraceId", "Ordinal");

                    b.ToTable("workflow_saga_decisions", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaLogicEvaluationEntity", b =>
                {
                    b.Property<Guid>("SagaCorrelationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("saga_correlation_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ticks");

                    b.Property<string>("FailureKind")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("failure_kind");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("failure_message");

                    b.Property<string>("LogsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("logs_json");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("node_id");

                    b.Property<string>("OutputPortName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("output_port_name");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("round_id");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.HasKey("SagaCorrelationId", "Ordinal");

                    b.HasIndex("TraceId", "Ordinal");

                    b.ToTable("workflow_saga_logic_evaluations", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaStateEntity", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("AgentVersionsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("agent_versions_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentAgentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("current_agent_key");

                    b.Property<string>("CurrentInputRef")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("current_input_ref");

                    b.Property<Guid>("CurrentNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("current_node_id");

                    b.Property<Guid>("CurrentRoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("current_round_id");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("current_state");

                    b.Property<int>("DecisionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("decision_count");

                    b.Property<string>("DecisionHistoryJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("decision_history_json");

                    b.Property<Guid?>("EscalatedFromNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("escalated_from_node_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("GlobalInputsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("global_inputs_json");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inputs_json");

                    b.Property<int>("LogicEvaluationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("logic_evaluation_count");

                    b.Property<string>("LogicEvaluationHistoryJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("logic_evaluation_history_json");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_node_id");

                    b.Property<Guid?>("ParentRoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_round_id");

                    b.Property<Guid?>("ParentTraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_trace_id");

                    b.Property<int>("RoundCount")
                        .HasColumnType("int")
                        .HasColumnName("round_count");

                    b.Property<int>("SubflowDepth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("subflow_depth");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("workflow_key");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("int")
                        .HasColumnName("workflow_version");

                    b.HasKey("CorrelationId");

                    b.HasIndex("ParentTraceId");

                    b.HasIndex("WorkflowKey", "WorkflowVersion");

                    b.ToTable("workflow_sagas", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleAssignmentEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.AgentRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleSkillGrantEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.AgentRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFlow.Persistence.SkillEntity", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleToolGrantEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.AgentRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CodeFlow.Persistence.McpServerToolEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.McpServerEntity", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowEdgeEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowEntity", "Workflow")
                        .WithMany("Edges")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowInputEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowEntity", "Workflow")
                        .WithMany("Inputs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowNodeEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowEntity", "Workflow")
                        .WithMany("Nodes")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaDecisionEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowSagaStateEntity", null)
                        .WithMany("Decisions")
                        .HasForeignKey("SagaCorrelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaLogicEvaluationEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowSagaStateEntity", null)
                        .WithMany("LogicEvaluations")
                        .HasForeignKey("SagaCorrelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowEntity", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Inputs");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaStateEntity", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("LogicEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
