// <auto-generated />
using System;
using CodeFlow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFlow.Persistence.Migrations
{
    [DbContext(typeof(CodeFlowDbContext))]
    [Migration("20260501120000_AssistantSettingsInstructions")]
    partial class AssistantSettingsInstructions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CodeFlow.Persistence.AgentConfigEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("ForkedFromKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("forked_from_key");

                    b.Property<int?>("ForkedFromVersion")
                        .HasColumnType("int")
                        .HasColumnName("forked_from_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRetired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_retired");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<string>("OwningWorkflowKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("owning_workflow_key");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwningWorkflowKey");

                    b.HasIndex("Key", "IsActive");

                    b.HasIndex("Key", "IsRetired");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleAssignmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("agent_key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("AgentKey");

                    b.HasIndex("RoleId");

                    b.HasIndex("AgentKey", "RoleId")
                        .IsUnique();

                    b.ToTable("agent_role_assignments", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsSystemManaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_managed");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("agent_roles", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleSkillGrantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("RoleId", "SkillId")
                        .IsUnique();

                    b.ToTable("agent_role_skill_grants", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleToolGrantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("category");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<string>("ToolIdentifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("tool_identifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "Category", "ToolIdentifier")
                        .IsUnique();

                    b.ToTable("agent_role_tool_grants", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AssistantConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ActiveWorkspaceSignature")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("active_workspace_signature");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("entity_type");

                    b.Property<long>("InputTokensTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("input_tokens_total");

                    b.Property<long>("OutputTokensTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("output_tokens_total");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("scope_key");

                    b.Property<int>("ScopeKind")
                        .HasColumnType("int")
                        .HasColumnName("scope_kind");

                    b.Property<Guid>("SyntheticTraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("synthetic_trace_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ScopeKey", "UpdatedAtUtc");

                    b.ToTable("assistant_conversations", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AssistantMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("InvocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("invocation_id");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("provider");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("assistant_messages", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.AssistantSettingsEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("key");

                    b.Property<long?>("AssignedAgentRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_agent_role_id");

                    b.Property<string>("Instructions")
                        .HasColumnType("longtext")
                        .HasColumnName("instructions");

                    b.Property<long?>("MaxTokensPerConversation")
                        .HasColumnType("bigint")
                        .HasColumnName("max_tokens_per_conversation");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Key");

                    b.HasIndex("AssignedAgentRoleId");

                    b.ToTable("assistant_settings", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.Authority.AgentInvocationAuthorityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("agent_key");

                    b.Property<int?>("AgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("agent_version");

                    b.Property<string>("BlockedAxesJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("blocked_axes_json");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("envelope_json");

                    b.Property<DateTime>("ResolvedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("round_id");

                    b.Property<string>("TiersJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tiers_json");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.Property<string>("WorkflowKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("workflow_key");

                    b.Property<int?>("WorkflowVersion")
                        .HasColumnType("int")
                        .HasColumnName("workflow_version");

                    b.HasKey("Id");

                    b.HasIndex("AgentKey", "ResolvedAtUtc");

                    b.HasIndex("TraceId", "ResolvedAtUtc");

                    b.ToTable("agent_invocation_authority", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.Authority.RefusalEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssistantConversationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assistant_conversation_id");

                    b.Property<string>("Axis")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("axis");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<string>("DetailJson")
                        .HasColumnType("longtext")
                        .HasColumnName("detail_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("path");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("stage");

                    b.Property<Guid?>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("AssistantConversationId", "OccurredAtUtc");

                    b.HasIndex("Stage", "OccurredAtUtc");

                    b.HasIndex("TraceId", "OccurredAtUtc");

                    b.ToTable("refusal_events", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.GitHostSettingsEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("key");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("base_url");

                    b.Property<byte[]>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("varbinary(1024)")
                        .HasColumnName("encrypted_token");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("mode");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.Property<int?>("WorkingDirectoryMaxAgeDays")
                        .HasColumnType("int")
                        .HasColumnName("working_directory_max_age_days");

                    b.HasKey("Key");

                    b.ToTable("git_host_settings", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.HitlTaskEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("agent_key");

                    b.Property<int>("AgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("agent_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("decided_at");

                    b.Property<string>("DeciderId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("decider_id");

                    b.Property<string>("Decision")
                        .HasColumnType("longtext")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionPayloadJson")
                        .HasColumnType("longtext")
                        .HasColumnName("decision_payload_json");

                    b.Property<string>("InputPreview")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("input_preview");

                    b.Property<string>("InputRef")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("input_ref");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("node_id");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("round_id");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("workflow_key");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("int")
                        .HasColumnName("workflow_version");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("TraceId", "RoundId", "AgentKey");

                    b.ToTable("hitl_tasks", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.LlmProviderSettingsEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("provider");

                    b.Property<string>("ApiVersion")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("api_version");

                    b.Property<byte[]>("EncryptedApiKey")
                        .HasColumnType("varbinary(1024)")
                        .HasColumnName("encrypted_api_key");

                    b.Property<string>("EndpointUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("endpoint_url");

                    b.Property<string>("ModelsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("models_json");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Provider");

                    b.ToTable("llm_providers", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.McpServerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("BearerTokenCipher")
                        .HasColumnType("varbinary(1024)")
                        .HasColumnName("bearer_token_cipher");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("endpoint_url");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Unverified")
                        .HasColumnName("health_status");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<string>("LastVerificationError")
                        .HasColumnType("text")
                        .HasColumnName("last_verification_error");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("transport");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("mcp_servers", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.McpServerToolEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsMutating")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_mutating");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("longtext")
                        .HasColumnName("parameters_json");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("synced_at");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "ToolName")
                        .IsUnique();

                    b.ToTable("mcp_server_tools", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.Notifications.NotificationDeliveryAttemptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("attempted_at");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<int>("EventKind")
                        .HasColumnType("int")
                        .HasColumnName("event_kind");

                    b.Property<string>("NormalizedDestination")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_destination");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("route_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "AttemptedAtUtc");

                    b.HasIndex("RouteId", "AttemptedAtUtc");

                    b.HasIndex("EventId", "ProviderId", "NormalizedDestination", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("notification_delivery_attempts", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.Notifications.NotificationProviderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalConfigJson")
                        .HasColumnType("longtext")
                        .HasColumnName("additional_config_json");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<byte[]>("EncryptedCredential")
                        .HasColumnType("varbinary(2048)")
                        .HasColumnName("encrypted_credential");

                    b.Property<string>("EndpointUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("endpoint_url");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("from_address");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_archived");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Channel");

                    b.ToTable("notification_providers", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.Notifications.NotificationRouteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<int>("EventKind")
                        .HasColumnType("int")
                        .HasColumnName("event_kind");

                    b.Property<int>("MinimumSeverity")
                        .HasColumnType("int")
                        .HasColumnName("minimum_severity");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("provider_id");

                    b.Property<string>("RecipientsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("recipients_json");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("template_id");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("int")
                        .HasColumnName("template_version");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("EventKind", "Enabled");

                    b.ToTable("notification_routes", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.Notifications.NotificationTemplateEntity", b =>
                {
                    b.Property<string>("TemplateId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("template_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body_template");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<int>("EventKind")
                        .HasColumnType("int")
                        .HasColumnName("event_kind");

                    b.Property<string>("SubjectTemplate")
                        .HasColumnType("longtext")
                        .HasColumnName("subject_template");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("TemplateId", "Version");

                    b.HasIndex("EventKind", "Channel");

                    b.ToTable("notification_templates", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.PromptPartialEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsSystemManaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_managed");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(192)
                        .HasColumnType("varchar(192)")
                        .HasColumnName("key");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("prompt_partials", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.Replay.ReplayAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DriftLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("drift_level");

                    b.Property<int>("Generation")
                        .HasColumnType("int")
                        .HasColumnName("generation");

                    b.Property<Guid>("LineageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lineage_id");

                    b.Property<Guid>("ParentTraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_trace_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<string>("ReplayState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("replay_state");

                    b.Property<string>("TerminalPort")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("terminal_port");

                    b.HasKey("Id");

                    b.HasIndex("LineageId");

                    b.HasIndex("ParentTraceId", "CreatedAtUtc");

                    b.ToTable("replay_attempts", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.SkillEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.TokenUsageRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("InvocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("invocation_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("model");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("node_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ScopeChainJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scope_chain_json");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UsageJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usage_json");

                    b.HasKey("Id");

                    b.HasIndex("InvocationId");

                    b.HasIndex("TraceId");

                    b.HasIndex("TraceId", "NodeId");

                    b.ToTable("token_usage_records", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowEdgeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("from_node_id");

                    b.Property<string>("FromPort")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("from_port");

                    b.Property<bool>("IntentionalBackedge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("intentional_backedge");

                    b.Property<bool>("RotatesRound")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("rotates_round");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("to_node_id");

                    b.Property<string>("ToPort")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("to_port");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "FromNodeId", "FromPort", "SortOrder");

                    b.ToTable("workflow_edges", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<int>("MaxRoundsPerRound")
                        .HasColumnType("int")
                        .HasColumnName("max_rounds_per_round");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tags_json");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("WorkflowVarsReadsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("workflow_vars_reads_json");

                    b.Property<string>("WorkflowVarsWritesJson")
                        .HasColumnType("longtext")
                        .HasColumnName("workflow_vars_writes_json");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowFixtureEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("FixtureKey")
                        .IsRequired()
                        .HasMaxLength(192)
                        .HasColumnType("varchar(192)")
                        .HasColumnName("fixture_key");

                    b.Property<string>("MockResponsesJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mock_responses_json");

                    b.Property<string>("StartingInput")
                        .HasColumnType("longtext")
                        .HasColumnName("starting_input");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(192)
                        .HasColumnType("varchar(192)")
                        .HasColumnName("workflow_key");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowKey", "FixtureKey")
                        .IsUnique();

                    b.ToTable("workflow_fixtures", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowInputEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DefaultValueJson")
                        .HasColumnType("longtext")
                        .HasColumnName("default_value_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("kind");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("required");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Key")
                        .IsUnique();

                    b.ToTable("workflow_inputs", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowNodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("agent_key");

                    b.Property<int?>("AgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("agent_version");

                    b.Property<string>("ContributorAgentKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("contributor_agent_key");

                    b.Property<int?>("ContributorAgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("contributor_agent_version");

                    b.Property<string>("CoordinatorAgentKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("coordinator_agent_key");

                    b.Property<int?>("CoordinatorAgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("coordinator_agent_version");

                    b.Property<string>("InputScript")
                        .HasColumnType("longtext")
                        .HasColumnName("input_script");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<double>("LayoutX")
                        .HasColumnType("double")
                        .HasColumnName("layout_x");

                    b.Property<double>("LayoutY")
                        .HasColumnType("double")
                        .HasColumnName("layout_y");

                    b.Property<string>("LoopDecision")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("loop_decision");

                    b.Property<string>("MirrorOutputToWorkflowVar")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("mirror_output_to_workflow_var");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("node_id");

                    b.Property<bool>("OptOutLastRoundReminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("opt_out_last_round_reminder");

                    b.Property<string>("OutputPortReplacementsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("output_port_replacements_json");

                    b.Property<string>("OutputPortsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("output_ports_json");

                    b.Property<string>("OutputScript")
                        .HasColumnType("longtext")
                        .HasColumnName("output_script");

                    b.Property<string>("OutputType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("string")
                        .HasColumnName("output_type");

                    b.Property<string>("RejectionHistoryConfigJson")
                        .HasColumnType("longtext")
                        .HasColumnName("rejection_history_config_json");

                    b.Property<int?>("ReviewMaxRounds")
                        .HasColumnType("int")
                        .HasColumnName("review_max_rounds");

                    b.Property<string>("SubflowKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("subflow_key");

                    b.Property<int?>("SubflowVersion")
                        .HasColumnType("int")
                        .HasColumnName("subflow_version");

                    b.Property<int?>("SwarmN")
                        .HasColumnType("int")
                        .HasColumnName("swarm_n");

                    b.Property<string>("SwarmProtocol")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("swarm_protocol");

                    b.Property<int?>("SwarmTokenBudget")
                        .HasColumnType("int")
                        .HasColumnName("swarm_token_budget");

                    b.Property<string>("SynthesizerAgentKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("synthesizer_agent_key");

                    b.Property<int?>("SynthesizerAgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("synthesizer_agent_version");

                    b.Property<string>("Template")
                        .HasColumnType("longtext")
                        .HasColumnName("template");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "NodeId")
                        .IsUnique();

                    b.ToTable("workflow_nodes", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaDecisionEntity", b =>
                {
                    b.Property<Guid>("SagaCorrelationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("saga_correlation_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("agent_key");

                    b.Property<int>("AgentVersion")
                        .HasColumnType("int")
                        .HasColumnName("agent_version");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionPayloadJson")
                        .HasColumnType("longtext")
                        .HasColumnName("decision_payload_json");

                    b.Property<string>("InputRef")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("input_ref");

                    b.Property<DateTime?>("NodeEnteredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("node_entered_at");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("node_id");

                    b.Property<string>("OutputPortName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("output_port_name");

                    b.Property<string>("OutputRef")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("output_ref");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("round_id");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.HasKey("SagaCorrelationId", "Ordinal");

                    b.HasIndex("TraceId", "Ordinal");

                    b.ToTable("workflow_saga_decisions", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaLogicEvaluationEntity", b =>
                {
                    b.Property<Guid>("SagaCorrelationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("saga_correlation_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ticks");

                    b.Property<string>("FailureKind")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("failure_kind");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("failure_message");

                    b.Property<string>("LogsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("logs_json");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("node_id");

                    b.Property<string>("OutputPortName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("output_port_name");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("round_id");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.HasKey("SagaCorrelationId", "Ordinal");

                    b.HasIndex("TraceId", "Ordinal");

                    b.ToTable("workflow_saga_logic_evaluations", (string)null);
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaStateEntity", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("AgentVersionsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("agent_versions_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentAgentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("current_agent_key");

                    b.Property<string>("CurrentInputRef")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("current_input_ref");

                    b.Property<Guid>("CurrentNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("current_node_id");

                    b.Property<DateTime>("CurrentRoundEnteredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("current_round_entered_at");

                    b.Property<Guid>("CurrentRoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("current_round_id");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("current_state");

                    b.Property<Guid?>("CurrentSwarmNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("current_swarm_coordinator_node_id");

                    b.Property<int>("DecisionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("decision_count");

                    b.Property<string>("DecisionHistoryJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("decision_history_json");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inputs_json");

                    b.Property<string>("LastEffectivePort")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("last_effective_port");

                    b.Property<int>("LogicEvaluationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("logic_evaluation_count");

                    b.Property<string>("LogicEvaluationHistoryJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("logic_evaluation_history_json");

                    b.Property<string>("ParentLoopDecision")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("parent_loop_decision");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_node_id");

                    b.Property<int?>("ParentReviewMaxRounds")
                        .HasColumnType("int")
                        .HasColumnName("parent_review_max_rounds");

                    b.Property<int?>("ParentReviewRound")
                        .HasColumnType("int")
                        .HasColumnName("parent_review_round");

                    b.Property<Guid?>("ParentRoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_round_id");

                    b.Property<Guid?>("ParentTraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_trace_id");

                    b.Property<string>("PendingParallelRoundIdsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("pending_parallel_round_ids_json");

                    b.Property<int>("RoundCount")
                        .HasColumnType("int")
                        .HasColumnName("round_count");

                    b.Property<int>("SubflowDepth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("subflow_depth");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trace_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("WorkflowInputsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("workflow_inputs_json");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("workflow_key");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("int")
                        .HasColumnName("workflow_version");

                    b.HasKey("CorrelationId");

                    b.HasIndex("ParentTraceId");

                    b.HasIndex("WorkflowKey", "WorkflowVersion");

                    b.ToTable("workflow_sagas", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleAssignmentEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.AgentRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleSkillGrantEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.AgentRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFlow.Persistence.SkillEntity", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CodeFlow.Persistence.AgentRoleToolGrantEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.AgentRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CodeFlow.Persistence.AssistantSettingsEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.AgentRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignedAgentRoleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CodeFlow.Persistence.McpServerToolEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.McpServerEntity", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowEdgeEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowEntity", "Workflow")
                        .WithMany("Edges")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowInputEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowEntity", "Workflow")
                        .WithMany("Inputs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowNodeEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowEntity", "Workflow")
                        .WithMany("Nodes")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaDecisionEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowSagaStateEntity", null)
                        .WithMany("Decisions")
                        .HasForeignKey("SagaCorrelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaLogicEvaluationEntity", b =>
                {
                    b.HasOne("CodeFlow.Persistence.WorkflowSagaStateEntity", null)
                        .WithMany("LogicEvaluations")
                        .HasForeignKey("SagaCorrelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowEntity", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Inputs");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("CodeFlow.Persistence.WorkflowSagaStateEntity", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("LogicEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
