namespace CodeFlow.Runtime.Authority;

/// <summary>
/// Append-only record of a denied / skipped / preflight-blocked piece of work, captured as
/// first-class evidence rather than as missing execution. Producers include the workspace
/// host tool (path-confinement / preimage / symlink / allowlist refusals from sc-270), the
/// authority envelope resolver (sc-269), preflight (sc-274), admitted handoff validators
/// (sc-272), and gates (sc-273). See sc-285 for the broader contract.
/// </summary>
/// <param name="Id">Stable refusal identifier (caller-supplied or generated by sink).</param>
/// <param name="TraceId">
/// Workflow trace correlation id, when the refusal occurred inside a workflow. Null for
/// pre-trace refusals (e.g. preflight that stops before any trace exists) and assistant
/// flows.
/// </param>
/// <param name="AssistantConversationId">
/// Homepage-assistant conversation id when the refusal happened inside an assistant
/// flow. Null for non-assistant refusals.
/// </param>
/// <param name="Stage">
/// Producer stage enum (string) — see <see cref="RefusalStages"/>. Stages name *where* the
/// refusal happened (preflight, admission, workspace, handoff, gate) and let governance
/// queries slice without parsing reason text.
/// </param>
/// <param name="Code">
/// Specific refusal code within the stage (e.g. <c>preimage-mismatch</c>,
/// <c>command-allowlist</c>, <c>envelope-tier</c>). Stable, machine-readable.
/// </param>
/// <param name="Reason">Human-readable explanation; safe to surface to operators and LLMs.</param>
/// <param name="Axis">
/// Optional finer-grained axis the refusal applied to — e.g. for envelope intersection
/// failures: <c>repoScope</c>, <c>tool-grant</c>, <c>network</c>, <c>budget</c>.
/// </param>
/// <param name="Path">Optional path the refusal targeted (workspace path, tool name, etc.).</param>
/// <param name="DetailJson">
/// Optional machine-readable detail blob (raw JSON). Producers should keep this small —
/// it is for evidence, not for full request bodies.
/// </param>
/// <param name="OccurredAt">UTC instant the refusal was produced.</param>
public sealed record RefusalEvent(
    Guid Id,
    Guid? TraceId,
    Guid? AssistantConversationId,
    string Stage,
    string Code,
    string Reason,
    string? Axis,
    string? Path,
    string? DetailJson,
    DateTimeOffset OccurredAt);

/// <summary>
/// Canonical stage names. Producers should reuse these constants so governance queries can
/// slice by stage without coordination.
/// </summary>
public static class RefusalStages
{
    public const string Preflight = "preflight";
    public const string Admission = "admission";
    public const string Workspace = "workspace";
    public const string Handoff = "handoff";
    public const string Gate = "gate";
    public const string Tool = "tool";
}
