namespace CodeFlow.Contracts.Notifications;

/// <summary>
/// Marker for provider-neutral notification events emitted by HITL/orchestration code.
/// Every event carries a stable <see cref="EventId"/> for idempotency, an <see cref="OccurredAtUtc"/>
/// timestamp, a <see cref="Kind"/> discriminator routes/templates filter on, an
/// <see cref="ActionUrl"/> reviewers click to handle the event, and an optional
/// <see cref="Severity"/> hint.
/// </summary>
/// <remarks>
/// Concrete event records (e.g. <see cref="HitlTaskPendingEvent"/>) hold their own payload
/// fields; the dispatcher accepts the marker so shared routing/render code does not need to
/// know every concrete type. The interface is deliberately empty of payload — keep
/// HITL-specific or future provider-specific data on the concrete record, not here.
/// </remarks>
public interface INotificationEvent
{
    /// <summary>
    /// Stable identifier for this event instance. Providers / dispatchers use it to dedupe
    /// retries and to correlate delivery attempts back to the source event.
    /// </summary>
    Guid EventId { get; }

    /// <summary>Discriminator routes and templates key off.</summary>
    NotificationEventKind Kind { get; }

    /// <summary>UTC time the event was generated by the orchestration layer.</summary>
    DateTimeOffset OccurredAtUtc { get; }

    /// <summary>
    /// Canonical CodeFlow deep-link reviewers should click to handle the event. Required.
    /// The URL format is owned by sc-62 (canonical HITL action links); this contract only
    /// enforces that one is present.
    /// </summary>
    Uri ActionUrl { get; }

    /// <summary>Optional severity hint (defaults to <see cref="NotificationSeverity.Normal"/>).</summary>
    NotificationSeverity Severity { get; }
}
